### ISSUE TITLE
Uri error

### ISSUE THREAD

**Issue by Prathapkarumanchi** [BlupGithub/Blup-IDE#2]
**main.dart:319:20: Error: The argument type 'Uri?' can't be assigned to the parameter type 'Uri' because 'Uri?' is nullable and 'Uri' isn't.
 - 'Uri' is from 'dart:core'.
      http.get(Uri.tryParse(requestURL),)**

<img width="1395" alt="Screenshot 2023-07-25 at 11 06 06 AM" src="https://github.com/BlupGithub/Blup_IDE/assets/53927098/642cb973-fa99-42f9-bd45-b2c5e4c4cc03">

**Comment by ashutosh2014** [comment]
Hi @Prathapkarumanchi, Thanks for finding the bug, will fix it in next update.

**Comment by ashutosh2014** [comment]
Hi @Prathapkarumanchi, the issue has been fixed now.
