### ISSUE TITLE
the whole page gets deleted while undo-ing 

### ISSUE THREAD

**Issue by HusainAmir** [BlupGithub/Blup-IDE#6]
When we create a new page and then draw a rectangle in it. Then if you undo it with ctrl+z, it removes the whole page that was created.

**Comment by HusainAmir** [comment]
@ashutosh2014 fix it asap.

**Comment by ashutosh2014** [comment]
Hi @HusainAmir, Thanks for reporting the issue, the issue is fixed now, and you will receive in 1.09 update.
